from best_response_equivalence import check_best_response_equivalence
from better_response_equivalence import check_better_response_equivalence
from order_preserving_equivalence import check_order_preserving_equivalence

def check_equivalence(reference_game, generated_game):
    pass




